kind: ConfigMap
apiVersion: v1
metadata:
  name: checkout-microservice-properties
data:
  spring.data.cassandra.keyspace-name: cronos
  spring.data.cassandra.contact-points: yb-tservers.yb-demo.svc.cluster.local
  spring.data.cassandra.port: "9042" 
