spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    serviceType: NodePort
    imagePullPolicy: Always
    group: nchandrappa